# Generated by Django 2.2.3 on 2019-07-31 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(max_length=200)),
                ('thumbnail_path', models.CharField(max_length=200)),
                ('modified_timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 12, 17, 40, 687091))),
            ],
        ),
    ]
