# Generated by Django 2.2.3 on 2019-07-31 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='modified_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 12, 17, 50, 783146)),
        ),
    ]
